### ISSUE TITLE
Update Action to use latest node

### ISSUE THREAD

**Issue by Nithos** [JulienKode/pull-request-name-linter-action#224]
GitHub is deprecating Node v12 support in its actions. Can we update this action to use Node 16 or 18.

[GitHub Notification](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12)

**Comment by miguel-fulfil** [comment]
@JulienKode is this github action still maintained? semantic-release is now requiring node 18+, and so being still on 12 seems like a big risk.

**Comment by JulienKode** [comment]
Hi @miguel-fulfil @Nithos 

Sorry this action is still maintained. It's just been a while since I didn't update node version and commitlint version.

I have a PR in progress to use a new node version: https://github.com/JulienKode/pull-request-name-linter-action/pull/226/
But seems there are some issues on it. I'll have to investigate

**Comment by chrisjohnson00** [comment]
For those of you wondering how to do this, but don't want to use this action due to the node12 runtime:

The below runs the same as the action. 
```
      - name: Install Dependencies
        # yamllint disable rule:line-length
        run: |
          npm install @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional'], rules: { 'subject-case': [0,'always',['sentence-case']],'header-max-length': [2, 'always', 120], 'body-max-line-length': [0, 'always', 120] }};" > commitlint.config.js
        # yamllint enable rule:line-length
      - name: Lint the PR Title
        run: |
          echo "${PR_TITLE}" | npx --yes commitlint
        env:
          PR_TITLE: '${{ github.event.pull_request.title }}'
```
