### ISSUE TITLE
Trailer-exists always fail

### ISSUE THREAD

**Issue by nascentcore-eng** [JulienKode/pull-request-name-linter-action#225]
A private repo has such github action configs:
```
      # https://github.com/JulienKode/pull-request-name-linter-action
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
        with:
          configuration-path: .commitlintrc.yml
```

The .commitlintrc.yml:

```
$ cat .commitlintrc.yml
---
# rules are documented at https://commitlint.js.org/#/reference-rules
# each rule has an array of three values:
# - 0, 1, 2 (rule is disabled, warning or error)
# - always/never
# - value
rules:
  # always sign off the commit
  # Cannot make this work, Signed-off-by: trailer in PR description is not
  # recognized.
  trailer-exists: [2, always, "Signed-off-by:"]
```

Then I have a Pull request with:
Title: `Chore: test pr body trailer`
Body: `Signed-off-by: Yaxiong Zhao`

But the check would constantly fail claiming

<img width="596" alt="Screen Shot 2023-01-09 at 22 16 48" src="https://user-images.githubusercontent.com/112656580/211328764-b2a468f2-7eae-4b5d-9816-6d42f185a1b6.png">

What's going on?
