### ISSUE TITLE
How to work with commitlint.config.ts (TypeScript config file)

### ISSUE THREAD

**Issue by joshuaja-tangelo** [JulienKode/pull-request-name-linter-action#235]
I'm getting this error when pointing to my `commitlint.config.ts` file. Here's my workflow file for reference. Any ideas so I don't have to go back to a js file for the commitlint config?

```
name: Verify pull request commit
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint pull request title
        uses: JulienKode/pull-request-name-linter-action@v0.5.0
        with:
          configuration-path: ./commitlint.config.ts

```
