### ISSUE TITLE
Default commitlint.config.js

### ISSUE THREAD

**Issue by Decat-SimonA** [JulienKode/pull-request-name-linter-action#30]
Hello, 

I just tried using this github action. I copy pasted this block from the README.md:
```yml
name: pr-name-linter
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: JulienKode/pull-request-name-linter-action@v0.1.0
```
but it throws:
```
Run JulienKode/pull-request-name-linter-action@v0.1.0
  with:
    configuration-path: ./commitlint.config.js
##[error]Error: ENOENT: no such file or directory, open '/home/runner/work/masterprice/masterprice/commitlint.config.js'
##[error]ENOENT: no such file or directory, open '/home/runner/work/masterprice/masterprice/commitlint.config.js'
```
Is it possible to provide a default configuration ?
Otherwise, what's the recommended way to configure it ?

**Comment by JulienKode** [comment]
Hi @Decat-SimonA,

We can make an update to provide a default commit lint configuration but the goal is to use one dedicated to your project. 
You can create a `commitlint.config.js` at the root of your project and put your linting commit configuration that will be applied to your pull request name

```javascript
module.exports = { extends: ["@commitlint/config-conventional"]  };
```

Let me know if it's solve your issue

**Comment by JulienKode** [comment]
I've made an example here: I hope you are safe and everything goes well for you 

I’ve made an example for you https://github.com/JulienKode/pull-request-name-linter-action-example

You are free to implement any module that you want as long as you install it in the workflow then the bundle can access to it:

https://github.com/JulienKode/pull-request-name-linter-action-example/blob/master/.github/workflows/test.yml

```yml
name: "test-pull-request-name"
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional
      - uses: JulienKode/pull-request-name-linter-action@v0.1.1
```
