### ISSUE TITLE
TypeError: normalizedName.indexOf is not a function

### ISSUE THREAD

**Issue by dominikfoldi** [JulienKode/pull-request-name-linter-action#61]
When the action runs it throws the following error:

```
Error: TypeError: normalizedName.indexOf is not a function
Error: normalizedName.indexOf is not a function
```

![image](https://user-images.githubusercontent.com/17691953/94834125-42b3ce80-0410-11eb-864d-b2b74d4ecbd7.png)

It seems that it is coming from the bundled `eslint`. Why `devDependencies` are bundled into the action's bundle in the first place? Isn't it possible to leave the `devDependencies` out with `ncc`?

I would really like to use your action but I don't have any experience with `ncc` so I cannot provide a PR unfortunately.

**Comment by JulienKode** [comment]
Hi @dominikfoldi 

To help you and debug on this can you show me your:
- package.json
- commitlint.config.js
- your github action

Then I'll have informations to help you and dive on this 

Have a nice day

**Comment by dominikfoldi** [comment]
Sure @JulienKode!

package.json
```
{
  "name": "my-project",
  "devDependencies": {
    "@commitlint/config-angular": "^11.0.0",
    "lerna": "^3.20.0",
  }
}
```

commitlint.config.js
```
const Project = require("@lerna/project");
const fs = require("fs");

const POC_FOLDER_PATH = "poc";

/**
 * Enum for scope requirements.
 */
const scopeRequirements = {
  REQUIRED: "required",
  OPTIONAL: "optional",
  FORBIDDEN: "forbidden"
};

/**
 * Valid types of commits with their scope requirements.
 */
const COMMIT_TYPES = {
  build: {
    name: "build",
    scope: scopeRequirements.OPTIONAL
  },
  release: {
    name: "release",
    scope: scopeRequirements.FORBIDDEN
  },
  docs: {
    name: "docs",
    scope: scopeRequirements.OPTIONAL
  },
  feat: {
    name: "feat",
    scope: scopeRequirements.REQUIRED
  },
  fix: {
    name: "fix",
    scope: scopeRequirements.REQUIRED
  },
  perf: {
    name: "perf",
    scope: scopeRequirements.REQUIRED
  },
  refactor: {
    name: "refactor",
    scope: scopeRequirements.REQUIRED
  },
  style: {
    name: "style",
    scope: scopeRequirements.OPTIONAL
  },
  test: {
    name: "test",
    scope: scopeRequirements.OPTIONAL
  },
  prot: {
    name: "prot",
    scope: scopeRequirements.REQUIRED
  },
  revert: {
    name: "revert",
    scope: scopeRequirements.FORBIDDEN
  },
};

/**
 * Our custom scopes
 */
const CUSTOM_SCOPES = ["packaging", "dev-docs"];

/**
 * Array of valid types.
 */
const types = Object.keys(COMMIT_TYPES);

/**
 * Construct the scopes array from the custom scopes, lerna package names and POC folder names.
 */
async function getScopes() {
  const lernaPackages = (await new Project().getPackages())
    .map(package => package.name)
    .map((name) => (name.charAt(0) === '@' ? name.split('/')[1] : name));
  const customScopes = CUSTOM_SCOPES;
  const pocs = fs.readdirSync(POC_FOLDER_PATH, { withFileTypes: true })
    .filter(file => file.isDirectory()).map(directory => directory.name);

  return [].concat(lernaPackages, customScopes, pocs);
}

/**
 * This rule checks if the scopes were used correctly.
 * @param type type of the commit 
 * @param scope optional scope of the commit message 
 */
function scopeRequirementRule({ type, scope }) {
  const scopeRequirement = COMMIT_TYPES[type].scope;

  if (scopeRequirement === scopeRequirements.FORBIDDEN && scope) {
    return [false, `scopes are forbidden for commits with type '${type}', but a scope of '${scope}' was provided`];
  }

  if (scopeRequirement === scopeRequirements.REQUIRED && !scope) {
    return [false, `scopes are required for commits with type '${type}', but no scope was provided`];
  }

  return [true];
}

module.exports = {
  extends: ["@commitlint/config-angular"],
  rules: {
    'scope-requirement-rule': [2, 'always'],
    'type-enum': [2, 'always', types],
    'scope-enum': getScopes().then(scopes => [2, 'always', scopes])
  },
  plugins: [
    {
      rules: {
        'scope-requirement-rule': scopeRequirementRule
      }
    }
  ]
};
```

lint-pr.yml
```
name: Lint PRs

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        run: npm ci

      - name: Lint the PR title to match our convention
        uses: JulienKode/pull-request-name-linter-action@v0.1.2
```


I left out the private/not relevant information.

Thank you!
